/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "EV3.hpp"
/* Header for class jEV3 */

#ifndef _Included_jEV3
#define _Included_jEV3
#ifdef __cplusplus
extern "C" {
#endif
#undef jEV3_MOTOR_A
#define jEV3_MOTOR_A 1L
#undef jEV3_MOTOR_B
#define jEV3_MOTOR_B 2L
#undef jEV3_MOTOR_C
#define jEV3_MOTOR_C 4L
#undef jEV3_MOTOR_D
#define jEV3_MOTOR_D 8L
#undef jEV3_PORT_1
#define jEV3_PORT_1 0L
#undef jEV3_PORT_2
#define jEV3_PORT_2 1L
#undef jEV3_PORT_3
#define jEV3_PORT_3 2L
#undef jEV3_PORT_4
#define jEV3_PORT_4 3L
#undef jEV3_PORT_A
#define jEV3_PORT_A 16L
#undef jEV3_PORT_B
#define jEV3_PORT_B 17L
#undef jEV3_PORT_C
#define jEV3_PORT_C 18L
#undef jEV3_PORT_D
#define jEV3_PORT_D 19L
#undef jEV3_STOP_FLOAT
#define jEV3_STOP_FLOAT 0L
#undef jEV3_STOP_BRAKE
#define jEV3_STOP_BRAKE 1L
/*
 * Class:     jEV3
 * Method:    _connect
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jEV3__1connect
  (JNIEnv *, jobject, jint);

/*
 * Class:     jEV3
 * Method:    _move
 * Signature: (BIJ)V
 */
JNIEXPORT void JNICALL Java_jEV3__1move
  (JNIEnv *, jobject, jbyte, jint, jlong);

/*
 * Class:     jEV3
 * Method:    _stop
 * Signature: (BIJ)V
 */
JNIEXPORT void JNICALL Java_jEV3__1stop
  (JNIEnv *, jobject, jbyte, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
